# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-04-11 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200409_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
