# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-04-09 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to=b'courses/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
    ]
